on: [push, workflow_dispatch]

name: build

jobs:

  ko-publish:
    name: Release ko artifact
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write  # OIDC support.
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: setup ko
      uses: imjasonh/setup-ko@v0.6
    - name: install cosign
      uses: sigstore/cosign-installer@main
    - name: Build binary and put into a container
      run: ko publish --bare github.com/bobcallaway/hello-ko
    - name: Sign the container using GitHub Actions Workload Identity
      run: COSIGN_EXPERIMENTAL=1 cosign sign -a git_sha=$GITHUB_SHA ghcr.io/bobcallaway/hello-ko
